name: healing_travelling
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  supercharged: ^2.1.1
  timeago: ^3.2.2

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hind-Light.ttf
          weight: 300
        - asset: assets/fonts/Hind-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hind-Bold.ttf
          weight: 700
